version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-local
    environment:
      SA_PASSWORD: "MinhaSenhaForte123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  relacionamentos-entidades:
    container_name: relacionamentos-entidades
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=dev

    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
